version: '2'

services:
  db:
    image: mariadb:10.3
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=wordpress
    ports:
      - "31306:3306"

  wordpress:
    build: 
      context: ./
    restart: always  
    links:
      - db:db
    depends_on: 
      - db
    ports:
      - "8999:80"
    volumes:
      - ./wordpresstest:/var/www/html
